tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'ethereum/ethereum'
tap 'tenderly/tenderly'
tap 'hpedrorodrigues/homebrew-tools'
tap 'hashicorp/tap'

# System
brew 'git'
brew 'openssl'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim'
brew 'neovim'
brew 'zsh'
brew 'htop'
brew 'tree'
brew 'mas'
brew 'defaultbrowser'
brew 'z'
brew 'ImageMagick'
cask 'rar'

# Programming language prerequisites and package managers
brew 'libyaml' # should come after openssl
brew 'coreutils'
brew 'yarn'
brew 'solidity'
brew 'typescript'
brew 'asdf'
brew 'tenderly'
cask 'gpg-suite'
brew 'hashicorp/tap/terraform'

# Common Apps
cask 'dockutil'
cask 'orbstack'
cask 'iterm2'
cask '1password'
cask '1password-cli'
cask 'dropbox'
cask 'google-chrome'
cask 'obsidian'
cask 'grammarly'
cask 'wechat'
cask 'discord'
cask 'zoom'
cask 'telegram'
cask 'microsoft-word'
cask 'microsoft-excel'
cask 'microsoft-outlook'
cask 'tencent-meeting'
cask 'voov-meeting'
cask 'readdle-spark'
